# Generated by Django 4.1.7 on 2023-02-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_contacts',
            field=models.ManyToManyField(to='telegrambot.service_contact'),
        ),
    ]
