# Generated by Django 4.1.7 on 2023-02-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_service_contact_service_service_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_contacts',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service_contact',
        ),
    ]
